### ISSUE TITLE
ตัว Control 7 และ 8 ซ้ำกัน และ Text Box ของ Grade ไม่มี

### ISSUE THREAD

**Issue by xNewz** [ComputerLab1-2564/Week-11#1]
# ตัว Control 7 และ 8 ซ้ำกัน ❗ #
##  👇 TextBox (textBoxGrade) ของ Grade ไม่มีครับ 👇 ##

![ภาพ](https://user-images.githubusercontent.com/50146617/141116863-a0711287-edd8-4831-a097-c5704e966c88.png)

**Comment by koson** [comment]
แก้แล้วครับ
